remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Recipe Ratings Unveiled: Predicting Success Through Steps, Time, and Ingredients"
description: "Author: Norah Kerendian"

# pages-themes/slate@v0.2.0